---
resources:
- name: scantron
  type: git
  source:
    uri: git@github.com:pivotalcf/scantron.git
    branch: master
    private_key: {{scantron-private-key}}

jobs:
- name: scantron
  plan:
  - get: scantron
    trigger: true
  - task: test
    file: scantron/ci/test.yml
